---
# Установка утилиты "mdadm" на ОС Debian
- include_tasks: install_debian.yml
  when: ansible_facts.os_family == "Debian"

# Установка утилиты "mdadm" на ОС RedHat
- include_tasks: install_RedHat.yml
  when: ansible_facts.os_family == "RedHat"

## Сборка Raid массива
- include_tasks: build.yml
